import java.util.Scanner;
fun main() {
    print("Student Enrollment No: ")
    var enroll = readLine()
    print("Student Name: ")
    var Name = readLine()
    print("Student Branch: ")
    var Branch = readLine()
    print("Student Class: ")
    var Class = readLine()
    print("Student Batch: ")
    var batch = readLine()
    print("Student College Name: ")
    var college_name = readLine()
    print("Student University Name: ")
    var university_name = readLine()
    print("Student Age: ")
    var age = readLine()
    println("Student Enrollment No: "+ enroll)
    println("Student Name: "+ Name)
    println("Student Branch: "+ Branch)
    println("Student Class: "+ Class)
    println("Student Batch: "+ batch)
    println("Student College Name: "+ college_name)
    println("Student University Name: "+ university_name)
    println("Student Age: "+ age)
}